language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
env: LD_LIBRARY_PATH=/usr/local/lib
dist: trusty
before_install:
    - git clone https://github.com/google/re2.git
    - cd re2 && make && sudo make install && cd ..

install:
    - pip install cffi six

script: python3 setup.py test
